# build stage
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

COPY configs/nginx.conf /etc/nginx/conf.d/
COPY configs/nginx/ssl /etc/nginx/ssl

RUN rm -rf /etc/nginx/conf.d/default.conf

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]